export const NOTE_SEARCH_PATTERN_SETTING = 'NOTE_SEARCH_PATTERN_SETTING';
export const NOTE_SEARCH_PATTERN_PLACEHOLDER = '$keyword';
export const REFERRER_SEARCH_PATTERN_SETTING = 'REFERRER_SEARCH_PATTERN_SETTING';
export const REFERRER_SEARCH_PATTERN_PLACEHOLDER = '$noteId';
export const REFERRER_LIST_HEADING_SETTING = 'REFERRER_LIST_HEADING_SETTING';
export const REFERRER_AUTO_LIST_SETTING = 'REFERRER_AUTO_LIST_SETTING';

export enum ReferrersAutoListPosition {
  None,
  NoteStart,
  NoteEnd,
}

export const MARKDOWN_SCRIPT_ID = 'MARKDOWN_SCRIPT_ID';
export const CODE_MIRROR_SCRIPT_ID = 'CODE_MIRROR_SCRIPT_ID';
